### ISSUE TITLE
move folders out trunk

### ISSUE THREAD

**Issue by caxqueiroz** [aaryani/CoreTardis#1]
Hi there, 
I will move the folders outside trunk. Doesn't make sense to have: CoreTardis/trunk/. 

Can I? 

Cheers,

**Comment by aaryani** [comment]
Please keep the trunk. There are more folders to be added at that level like
DOCS.

At this stage I would keep the structure as it is.

Thanks.
Amir

**Comment by aaryani** [comment]
I suggest we review the code architecture in the next meeting.

amir

**Comment by aaryani** [comment]
I understand that Trunk is no longer needed after migrating to GitHub. I am happy if you remove it.
